In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [25]:
#Check whether a given matrix is a stochastic matrix
def checkTransitionMatrix(T):
    bool = 1
    n,m = T.shape
    for i in range(0,n):
        if sum(T[i,:]) != 1:
            bool = 0
            break
    return bool

In [13]:
class MSM:
    
    def __init__(self,T):
        self.T = T
        
    def stationarydistribution(self):
        EW,EV = linalg.eig(transpose(T))
        statdist = EV[:,0] / sum(EV[:,0])
        return statdist
    
    def eigenvalues(self):
        EW, EV = linalg.eig(T)
        return EW
    
    def timescales(self):
        EW = self.eigenvalues()
        t = []
        for i in range(0,len(EW)):
            t.append(-1 / log(EW[i]))
        return t
    
    def TPT(self):
        qminus = np.ones(len(T))
        qplus  = np.ones(len(T))
        n = len(qminus)
        f = np.zeros(shape=(n,n)) # discrete prob. curr.
        pi = self.stationarydistribution()
        effprobcur = np.zeros(shape=(n,n))
        FAB = 0
        set = [1,2]
        for i in range(0,n):
            for j in range(0,n):
                if (i != j):

                    f[i,j] = pi[i]*qminus[i]*T[i,j]*qplus[j]
                    f[j,i] = pi[j]*qminus[j]*T[j,i]*qplus[i]
                    effprobcur[i,j] = max(0,(f[i,j]- f[j,i]))

                    if (i in set):
                        FAB = FAB + effprobcur[i,j]

        KAB = FAB / dot(pi,qminus)
        return f, effprobcur, FAB, KAB

In [37]:
T = np.array([[0.5, 0.5],[0.5,0.5]])

In [10]:
testmsm = MSM(T)

In [41]:
pi = testmsm.stationarydistribution()
pi

array([ 1.,  0.])

In [11]:
testmsm.TPT()

(array([[ 0.        ,  0.27272727],
        [ 0.27272727,  0.        ]]),
 array([[  0.00000000e+00,   0.00000000e+00],
        [  5.55111512e-17,   0.00000000e+00]]),
 5.5511151231257827e-17,
 5.5511151231257827e-17)

In [12]:
testmsm.timescales()

C:\Users\Niklas\Anaconda\lib\site-packages\IPython\kernel\__main__.py:19: RuntimeWarning: invalid value encountered in log


[-9007199254740992.0, nan]

In [19]:
s = T.shape

In [38]:
# Check whether a given matrix is stochastic and its transposed, too
def checkDoublyStochastic(T):
    TMbool = checkTransitionMatrix(T)
    DSbool = 1
    [n,m] = T.shape
    for i in range(0,m):
        if (sum(T[:,i]) != 1):
            DSbool = 0
            break
    return DSbool

In [39]:
checkDoublyStochastic(T)

1