In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [34]:
def statdist(T):
    EW,EV = linalg.eig(transpose(T))
    statdist = EV[:,0] / sum(EV[:,0])
    return statdist

In [7]:
# hitting times: (not the hitting probabilities computet via the transition matrix! Only for a given chain!)
def hittingtimes(chain, set):
    
    for t in range(0, len(chain) -1):
        if (chain[t] in set):
            break
    return t

In [8]:
def meanhittingtime(chain):
    HTs = []
    counter = 0
    for i in range(min(chain), max(chain)+1):
        HTs.append(hittingtimes(chain,[i]))
    meanHT = sum(HTs)/len(HTs)
    return meanHT

In [46]:
# TPT analysis involving the discrete and effective prob. current, number of reactive trajectories, mean first passage time.
# I don't know yet how to compute forward and backward committors
def TPT(T, qminus, qplus):
    n = len(qminus)
    f = np.zeros(shape=(n,n)) # discrete prob. curr.
    pi = statdist(T)
    effprobcur = np.zeros(shape=(n,n))
    FAB = 0
    set = [1,2]
    for i in range(0,n):
        for j in range(0,n):
            if (i != j):

                f[i,j] = pi[i]*qminus[i]*T[i,j]*qplus[j]
                f[j,i] = pi[j]*qminus[j]*T[j,i]*qplus[i]
                effprobcur[i,j] = max(0,(f[i,j]- f[j,i]))

                if (i in set):
                    FAB = FAB + effprobcur[i,j]

    KAB = FAB / dot(pi,qminus)
    return f, effprobcur, FAB, KAB



In [37]:
# Test for stat. dist.
T = np.array([ [0.4, 0.4, 0.2],[0.1,0.2, 0.7], [0.5, 0.4, 0.1]])
EV, EW = linalg.eig(T)
st = statdist(T)
print st
print dot(transpose(st),linalg.matrix_power(T,3))

[ 0.33333333  0.33333333  0.33333333]
[ 0.33333333  0.33333333  0.33333333]


In [48]:
# Test for TPT
qminus = [1, 1, 0.4] #dummies for qminus and qplus
qplus = [0.3, 0.2, 1]
f, eff, FAB, KAB = TPT(T,qminus,qplus)
KAB

0.29213973799126658

array([ 0.26455026,  0.28042328,  0.45502646])

4

2


2

0.47537325255502216